name: OreArea
main: ore.area.AreaMainClass
version: 1.3.3
api:
  - 1.0.9
author: 若水
load: POSTWORLD
loadbefore:
  - AutoUpData

permissions:
  ore.area.kq:
    description: "矿区主命令"
    default: true
  ore.area.kq.pos:
    description: "选择坐标"
    default: op
  ore.area.kq.create:
    description: "创建矿区"
    default: op
  ore.area.kq.open:
    description: "开启矿区"
    default: op
  ore.area.kq.close:
    description: "关闭矿区"
    default: op
  ore.area.kq.transfer:
    description: "传送矿区"
    default: true
  ore.area.kq.setprice:
    description: "设置传送到一个矿区价格"
    default: op
  ore.area.kq.settransfer:
    description: "设置矿区传送点"
    default: op
  ore.area.kq.setmoney:
    description: "设置矿区解锁价格"
    default: op
  ore.area.kq.setUseTime:
    description: "设置玩家使用时间"
    default: op
  ore.area.kq.setlast:
    description: "设置解锁矿区前先解锁"
    default: op
  ore.area.kq.delete:
    description: "删除矿区"
    default: op
  ore.area.kq.refresh:
    description: "刷新矿区"
    default: op
  ore.area.kq.addcount:
    description: "增加进入次数"
    default: op
  ore.area.kq.setLevel:
    description: "设置矿区等级"
    default: op
  ore.area.kq.clear:
    description: "清空矿区"
    default: op
  ore.area.kq.reload:
    description: "重载配置文件"
    default: op
  ore.area.kq.success:
    description: "设置方块成就"
    default: op
  ore.area.kq.cb:
    description: "设置方块回收价格"
    default: op
  ore.area.kq.sellinv:
    description: "回收玩家背包内方块"
    default: true
  ore.area.kq.show:
    description: "让执行者显示矿区GUI"
    default: true
  ore.area.kq.drop:
    description: "设置矿区是否死亡掉落"
    default: op
  ore.area.kq.pvp:
    description: "设置矿区是否允许PVP"
    default: op
  ore.area.kq.usecount:
    description: "设置矿区的使用次数"
    default: op



