#   ___              _
#  / _ \ _ __ ___   / \   _ __ ___  __ _
# | | | | '__/ _ \ / _ \ | '__/ _ \/ _` |
# | |_| | | |  __// ___ \| | |  __/ (_| |
#  \___/|_|  \___/_/   \_\_|  \___|\__,_|
# 设置后 矿区只在 固定的时间刷新 否则不限制
刷新矿区时间段:
  - "12:30 - 17:00"

# 玩家进入矿区后 的一个提示
进入矿区是否提示: true

# 玩家离开矿区后的提示
离开矿区是否提示: true

# 可以设置不同的提示类型
# title: 大标题
# tip: 底部显示 （tip类型）
# popup: 底部显示 （popup类型）
# action: 底部显示 （actionbar类型）
# boss boss血条显示
# msg: 普通消息提示
提示类型: title


# 开启后 玩家需要购买才可以传送至矿区
是否开启玩家购买解锁: true

# x秒后传送至矿区 (使用矿区GUI传送)
传送时间: 5

# 是否显示传送粒子
是否显示粒子: true

# 玩家传送矿区提示
玩家传送到矿区是否提示: true

玩家传送到矿区提示: title
# false 为只给玩家自身发消息
玩家传送矿区是否全服公告: false

# 玩家解锁矿区发送公告
玩家解锁矿区是否公告: true

#开启则保护整个矿区世界
是否保护矿区: false

#当玩家背包满后不再发送
掉落物是否直接发送背包: true
